### ISSUE TITLE
Correct forwarding of HTTP reponse codes

### ISSUE THREAD

**Issue by mustafayousef** [gotenberg/gotenberg#747] opened 2023-12-12 09:38 UTC
Hello,

I'm attempting to retrieve a .docx document ( via /forms/chromium/convert/url ) from a server that demands authentication. The type of authentication needed isn't relevant. The issue I'm encountering is that although the server appropriately responds with a 401: Unauthorized status (as expected), Gotenberg, in contrast, responds with a misleading 200: OK status, creating confusion.

My recommendation is to ensure that Gotenberg accurately mirrors the correct response codes from the server.

**Comment by gulien** [comment] 2023-12-12 10:18
Duplicate of #613.

**Closed by gulien** 2023-12-12 10:18 UTC
