### ISSUE TITLE
gotenberg doesn't apply page sizing to excel file conversion when sheet is just a large figure

### ISSUE THREAD

**Issue by PrathamSoni** [gotenberg/gotenberg#799] opened 2024-02-12 23:58 UTC
despite adding scale and page size options the figure is still cut between multiple pages. also, landscape is only applied to some pages.

**Comment by PrathamSoni** [comment] 2024-02-13 02:10
@gulien  can you add this option for single page sheets: 'pdf:calc_pdf_Export:{"SinglePageSheets":{"type":"boolean","value":"true"}}'

**Comment by gulien** [comment] 2024-02-13 09:33
Closing this as duplicate of #36

**Closed by gulien** 2024-02-13 09:33 UTC
