### ISSUE TITLE
PDF generated add 2 white/blank pages

### ISSUE THREAD

**Issue by 04116** [gotenberg/gotenberg#566] opened 2022-12-23 04:41 UTC
![image](https://user-images.githubusercontent.com/36094827/209272100-b1a64524-10c5-4d82-b333-9651c2430c75.png)
Hi team,
Please check image

**Comment by gulien** [comment] 2023-01-02 08:37
Which module are you using? Might not be related to Gotenberg also.

**Comment by karatekaneen** [comment] 2023-01-11 13:50
@gulien I encountered the same problem in version 7.7.2 and I got 600 blank pages 😆 

When downgraded to 7.6.1 I only got one blank page but that might be due to our styling or content and that's not really a problem. 

This is the request that I ran against both versions. The page is a single page application that is rendered on the client side

```sh
curl \
--request POST 'http://localhost:3000/forms/chromium/convert/url' \
--form 'url="https://content.company.com"' \
--form 'marginTop="1"' \
--form 'marginBottom="1"' \
--form 'marginLeft="1"' \
--form 'marginRight="1"' \
--form 'waitForExpression="Boolean(document.getElementsByClassName(`last-item`).length)"' \
-o my.pdf
```

**Comment by karatekaneen** [comment] 2023-01-16 10:33
This is a Chrome issue. There's supposedly some workarounds but I haven't gotten any of them to work for my case yet. Maybe you have better luck: https://support.google.com/chrome/thread/191619088?hl=en&msgid=192661374

I could reproduce this issue on the latest version of Chrome (`108.0.5359.124`) on MacOS

**Comment by karatekaneen** [comment] 2023-01-25 10:28
@gulien What would you say if I suggest to [downgrade Chromium](https://support.google.com/chrome/thread/191619088?hl=en&msgid=192706871) until this upstream issue is resolved?

**Comment by gulien** [comment] 2023-01-25 13:28
@karatekaneen let me know when a working Chrome version is available as stable 👍

**Comment by karatekaneen** [comment] 2023-03-15 09:36
Just tried the print to pdf in the latest version of Chrome on Mac (111.0.5563.64) and the blank pages are gone.
However, now the page breaks are not respected again (as mentioned [here](https://github.com/gotenberg/gotenberg/discussions/582)) but I'm pretty sure that it's a separate issue in Chrome as well.

**Comment by gulien** [comment] 2023-03-31 14:52
Closing this issue as Gotenberg 7.8.2 brings Chrome `111.0.5563.146`. Thanks @karatekaneen for help!

**Closed by gulien** 2023-03-31 14:52 UTC
Labels: bug, chromium
