### ISSUE TITLE
URL to PDF: HTTP error status from upstream server produces PDF with error response from upstream

### ISSUE THREAD

**Issue by dselph** [gotenberg/gotenberg#801] opened 2024-02-16 02:59 UTC
We are passing a URL to gotenberg which returns HTML, converting to PDF, and using the webhook functionality to PUT the PDF to S3. When the upstream server encounters an error and returns a 500 response code, we end up with a PDF of the HTTP response saved to S3.

I would expect this to result in no PDF being PUT for the request whose URL produced an error.

Is this expected behavior? Or a known issue?

**Comment by gulien** [comment] 2024-02-16 09:01
Hello @dselph,

I suppose those were generated before the 8.0.0 release? Indeed, in versions 7.x.x, Gotenberg was printing to PDF whatever the upstream server responded, e.g., error page etc.

Since 8.0.0 release, it should not be the case anymore (https://gotenberg.dev/docs/routes#invalid-http-status-codes-chromium).

**Comment by dselph** [comment] 2024-02-16 14:26
Thank you for the reply.

We are actually running v8.0.2, but had overlooked that option for invalid http status codes. That does lead to a better result, as the generated PDF does not contain the original error response, but it does still generate a PDF, which is undesired behavior.

We will get the HTML in our app and only call gotenberg with it when we get a valid response so that we have more control over that behavior. Thanks again!

**Comment by gulien** [comment] 2024-02-16 15:05
The default option value (e.g., all errors from 400 to 599) should be enough for most if not all scenarios.

Anyway, I try to reproduce your issue but without success 🤔 

---

Success workflow ✅ 

```bash
curl --request POST \
  --url https://demo.gotenberg.dev/forms/chromium/convert/url \
  --header 'Content-Type: multipart/form-data' \
  --header 'Gotenberg-Trace: debug' \
  --header 'Gotenberg-Webhook-Error-Url: https://en2ccqa3tgqllm2.m.pipedream.net' \
  --header 'Gotenberg-Webhook-Url: https://enz2x603f0k4rr5.m.pipedream.net' \
  --form url=https://httpstat.us/200 \
  --form skipNetworkIdleEvent=true
```

<img width="778" alt="Capture d’écran 2024-02-16 à 16 02 12" src="https://github.com/gotenberg/gotenberg/assets/8983173/9dd999a0-d2a3-47bf-ba09-483c29288903">

---

Error workflow 🔴 

```bash
curl --request POST \
  --url https://demo.gotenberg.dev/forms/chromium/convert/url \
  --header 'Content-Type: multipart/form-data' \
  --header 'Gotenberg-Trace: debug' \
  --header 'Gotenberg-Webhook-Error-Url: https://en2ccqa3tgqllm2.m.pipedream.net' \
  --header 'Gotenberg-Webhook-Url: https://enz2x603f0k4rr5.m.pipedream.net' \
  --form url=https://httpstat.us/400 \
  --form skipNetworkIdleEvent=true
```

<img width="649" alt="Capture d’écran 2024-02-16 à 16 02 29" src="https://github.com/gotenberg/gotenberg/assets/8983173/a58c4714-3ab5-45b6-9581-09407b08ce97">

---

Notice that:

1. In both scenarios, the correct URL is called (e.g., Gotenberg-Webhook-Url & Gotenberg-Webhook-Error-Url)
2. In case of error, the error is correctly returned and no PDF is generated.

**Comment by gulien** [comment] 2024-02-21 09:31
Closing this issue, please re-open it if you find a way to reproduce your issue.

**Closed by gulien** 2024-02-21 09:31 UTC
